import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useState } from 'react'

export default function Home() {

  const [brand, setBrand] = useState('')
  const [model, setModel] = useState('')
  const [price, setPrice] = useState('')

  const handleBrandChange = (event) => {
    const value = event.target.value;
    setBrand(value)
  }

  const handleModelChange = (event) => {
    const value = event.target.value;
    setModel(value)
  }

  const handlePriceChange = (event) => {
    const value = event.target.value;
    setPrice(value)
  }

  const handleSubmit = async () => {
    const data = {
      brand, model, price
    }

    const body = JSON.stringify(data)
    const requestOptions = {
      method: 'POST',
      headers: {
        'Content-type':'application/json'
      },
      body
    }
    const response = await fetch('http://localhost:3000/api/laptopInventory', requestOptions);
        const json = await response.json();

        console.log(json);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Quiz3-ntan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>
        Brand
        <input type='text' value={brand} onChange={handleBrandChange}/>
      </p>
      <p>
        Model
        <input type='text' value={model} onChange={handleModelChange} />
      </p>
      <p>
        Price
        <input type='text' value={price} onChange={handlePriceChange}/>
      </p>
      <button onClick={handleSubmit}>Submit</button>
     
    </div>
  )
}
